fix sql bug
Error: near "VALUES": syntax error in SELECT rowid FROM fsrs WHERE word VALUES ?1; at offset 34

Caused by:
    0: near "VALUES": syntax error in SELECT rowid FROM fsrs WHERE word VALUES ?1; at offset 34
    1: Error code 1: SQL error or missing database

rustc 1.88.0-nightly (d5b4c2e4f 2025-04-02)